### ISSUE TITLE
Allow $request_uri in REDIRECT_LOCATION

### ISSUE THREAD

**Issue by lukecyca** [adamkdean/redirect#1]
Often when redirecting between www and non-www, and between http and https, the path is included. For example using this nginx config:

```
return 301 https://www.vhost.domain.tld$request_uri;
```

I don't think that's possible with this docker image. It would be great if it was.

**Comment by MaximStone** [comment]
I am agree

**Comment by adamkdean** [comment]
Apologies @lukecyca @MaximStone, I didn't see this issue. This has now been resolved in #3 (thanks @dweevedi)
